name = "amb-daily-reporting"
main = "worker.js"
compatibility_date = "2026-08-01"

[triggers]
crons = ["* * * * *", "45 3 * * 1-5"]

[[kv_namespaces]]
binding = "LASTSEEN"
id = "31aa44633f0b43b1bacd1f2f1ce489da"
